version: "3.9"
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: QUALITUS
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - internalnet

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - internalnet

  server:
    build: ./Server
    restart: always
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: QUALITUS
    ports:
      - "3000:3000"
    volumes:
      - chargements:/app/chargements
    depends_on:
      - db
    networks:
      - internalnet

  view:
    build:
      context: ./Views
      dockerfile: Dockerfile.dev  
    restart: always
    ports:
      - "4200:4200"
    volumes:
      - ./Views:/app           # hot reload
      - /app/node_modules      # ne pas écraser node_modules
    depends_on:
      - server
    networks:
      - internalnet

volumes:
  db-data:
  chargements:

networks:
  internalnet:
    driver: bridge
