# Dockerfile pour Angular dev
FROM node:20 AS dev
WORKDIR /app

# Copier package.json et installer dépendances
COPY package*.json ./
RUN npm install --legacy-peer-deps

# Copier le reste du code
COPY . .

# Exposer le port Angular
EXPOSE 4200

# Lancer Angular avec hot reload et proxy vers backend
CMD ["npm", "run", "start", "--", "--host", "0.0.0.0", "--port", "4200", "--proxy-config", "proxy.config.js"]
